# Generated by Django 4.2.1 on 2023-08-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
